server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8081
          predicates:
            - Path=/stocks/** 
        - id: delivery
          uri: http://localhost:8082
          predicates:
            - Path=/deliveries/**,/cancellations/**
        - id: statusview
          uri: http://localhost:8083
          predicates:
            - Path= /customerpages/**
        - id: payment
          uri: http://localhost:8084
          predicates:
            - Path=/payments/**,/paymentCancellations/**
        - id: stock
          uri: http://localhost:8085
          predicates:
            - Path=/orders/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/stocks/** 
        - id: delivery
          uri: http://delivery:8080
          predicates:
            - Path=/deliveries/**,/cancellations/**
        - id: statusview
          uri: http://statusview:8080
          predicates:
            - Path= /customerpages/**
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/**,/paymentCancellations/**
        - id: stock
          uri: http://stock:8080
          predicates:
            - Path=/orders/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
